In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
#  Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.0],
              [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
            [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Create a dataframe from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating Arrays

In [14]:
sampleArray = np.array([1, 2, 3])
sampleArray

array([1, 2, 3])

In [15]:
sampleArray.dtype

dtype('int64')

In [16]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((2,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
rangeArray= np.arange(1, 10, 2)

In [22]:
rangeArray

array([1, 3, 5, 7, 9])

In [23]:
randomArray = np.random.randint(0, 10,size=(3,5))

In [24]:
randomArray

array([[3, 0, 5, 5, 8],
       [5, 9, 2, 3, 4],
       [0, 9, 8, 6, 2]])

In [26]:
randomArray.size, randomArray.shape

(15, (3, 5))

In [30]:
randomArray2 = np.random.random((7,3))
randomArray2

array([[0.03357101, 0.64072108, 0.93776431],
       [0.590653  , 0.27164021, 0.107214  ],
       [0.59119278, 0.55374903, 0.47652171],
       [0.01433434, 0.42967958, 0.4133158 ],
       [0.40780224, 0.35729484, 0.29176408],
       [0.31268153, 0.47498783, 0.63258805],
       [0.42604168, 0.41640327, 0.31641936]])

In [31]:
randomArray2.size, randomArray2.shape

(21, (7, 3))

In [33]:
randomArray3 = np.random.rand(7, 3)
randomArray3

array([[0.25718226, 0.06545046, 0.36239126],
       [0.06301199, 0.73899404, 0.36267232],
       [0.51499036, 0.81607916, 0.69106528],
       [0.55219989, 0.61508886, 0.08476862],
       [0.03304591, 0.87671455, 0.5060993 ],
       [0.1985    , 0.94632843, 0.53669344],
       [0.091715  , 0.65197727, 0.47726052]])

In [38]:
# Pseudo-random numbers
np.random.seed(seed = 0) # same random number 
randomArray4 = np.random.randint(10, size= (5, 3))
randomArray4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [40]:
randomArray4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [41]:
np.unique(randomArray4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [49]:
np.random.seed(0)
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [52]:
a4

array([[[[5, 0, 3, 3, 7],
         [9, 3, 5, 2, 4],
         [7, 6, 8, 8, 1],
         [6, 7, 7, 8, 1]],

        [[5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1]],

        [[9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9]]],


       [[[8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3]],

        [[4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2]],

        [[0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2]]]])

In [47]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [53]:
# Get the first 4 numbers of innermost arrays
a4[:, :, :, :1]

array([[[[5],
         [9],
         [7],
         [6]],

        [[5],
         [3],
         [2],
         [3]],

        [[9],
         [3],
         [0],
         [8]]],


       [[[8],
         [9],
         [0],
         [4]],

        [[4],
         [7],
         [5],
         [0]],

        [[0],
         [5],
         [2],
         [2]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [57]:
a1 

array([1, 2, 3])

In [59]:
ones = np.ones(3)

In [62]:
ones

array([1., 1., 1.])

In [64]:
a1 + ones

array([2., 3., 4.])

In [65]:
a1 - ones

array([0., 1., 2.])

In [66]:
a1 * ones

array([1., 2., 3.])

In [67]:
a2 

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [68]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [69]:
# How to reshape a2  to  make it compatible with a3?
# 
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [70]:
a1 / ones

array([1., 2., 3.])

In [71]:
# Floor division removes decimal(rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [72]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [74]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [75]:
np.add(a1, ones)

array([2., 3., 4.])

In [76]:
a1 % 2

array([1, 0, 1])

In [77]:
a2 % 2

array([[1. , 0. , 1. ],
       [0. , 1. , 0.5]])

In [78]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation
Aggregation = performing same operation on a number of things 

In [79]:
list_list = [1,2,3]

In [80]:
type(list_list)

list

In [82]:
sum(list_list)

6

In [83]:
sum(a1)

6

In [84]:
np.sum(a1)

6

In [85]:
type(sum(a1))

numpy.int64

In [86]:
type(np.sum(a1))

numpy.int64

Use Python's methods `sum()` on Python datatypes and Numpy's methods on NumPy arrays `np.sum()`

In [91]:
# ccreate a massive Numpy array
np.random.seed(0)
massiveArray = np.random.random(100000)
massiveArray.size

100000

In [92]:
massiveArray

array([0.5488135 , 0.71518937, 0.60276338, ..., 0.81013284, 0.55103228,
       0.22575586])

In [93]:
massiveArray[:10]

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [94]:
%timeit sum(massiveArray) # Python's sum
%timeit np.sum(massiveArray) # NumPy's sum

32.8 ms ± 4.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
103 µs ± 11.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [95]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [96]:
np.mean(a2)

3.5833333333333335

In [97]:
np.max(a2)

6.5

In [98]:
# Standard deviation = a measure of how spread out a group of numbers is from each other
np.std(a2)

1.8352262954621035

In [99]:
# Variance = measure of average degree to which each number is different
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.368055555555556

In [100]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2)) 

1.8352262954621035