In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
#  Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.0],
              [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
            [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Create a dataframe from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating Arrays

In [14]:
sampleArray = np.array([1, 2, 3])
sampleArray

array([1, 2, 3])

In [15]:
sampleArray.dtype

dtype('int64')

In [16]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((2,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
rangeArray= np.arange(1, 10, 2)

In [22]:
rangeArray

array([1, 3, 5, 7, 9])

In [23]:
randomArray = np.random.randint(0, 10,size=(3,5))

In [24]:
randomArray

array([[3, 0, 5, 5, 8],
       [5, 9, 2, 3, 4],
       [0, 9, 8, 6, 2]])

In [26]:
randomArray.size, randomArray.shape

(15, (3, 5))

In [30]:
randomArray2 = np.random.random((7,3))
randomArray2

array([[0.03357101, 0.64072108, 0.93776431],
       [0.590653  , 0.27164021, 0.107214  ],
       [0.59119278, 0.55374903, 0.47652171],
       [0.01433434, 0.42967958, 0.4133158 ],
       [0.40780224, 0.35729484, 0.29176408],
       [0.31268153, 0.47498783, 0.63258805],
       [0.42604168, 0.41640327, 0.31641936]])

In [31]:
randomArray2.size, randomArray2.shape

(21, (7, 3))

In [33]:
randomArray3 = np.random.rand(7, 3)
randomArray3

array([[0.25718226, 0.06545046, 0.36239126],
       [0.06301199, 0.73899404, 0.36267232],
       [0.51499036, 0.81607916, 0.69106528],
       [0.55219989, 0.61508886, 0.08476862],
       [0.03304591, 0.87671455, 0.5060993 ],
       [0.1985    , 0.94632843, 0.53669344],
       [0.091715  , 0.65197727, 0.47726052]])

In [ ]:
# Pseudo-random numbers
np.random.seed()